// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package paymentmethodmock

import (
	"billsplitter-monolith/internal/domain/payment_method"
	"billsplitter-monolith/internal/domain/valueobject"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, paymentMethod payment_method.PaymentMethod) (payment_method.PaymentMethod, error) {
	ret := _mock.Called(ctx, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 payment_method.PaymentMethod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, payment_method.PaymentMethod) (payment_method.PaymentMethod, error)); ok {
		return returnFunc(ctx, paymentMethod)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, payment_method.PaymentMethod) payment_method.PaymentMethod); ok {
		r0 = returnFunc(ctx, paymentMethod)
	} else {
		r0 = ret.Get(0).(payment_method.PaymentMethod)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, payment_method.PaymentMethod) error); ok {
		r1 = returnFunc(ctx, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentMethod payment_method.PaymentMethod
func (_e *MockService_Expecter) Create(ctx interface{}, paymentMethod interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, paymentMethod)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, paymentMethod payment_method.PaymentMethod)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 payment_method.PaymentMethod
		if args[1] != nil {
			arg1 = args[1].(payment_method.PaymentMethod)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(paymentMethod1 payment_method.PaymentMethod, err error) *MockService_Create_Call {
	_c.Call.Return(paymentMethod1, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, paymentMethod payment_method.PaymentMethod) (payment_method.PaymentMethod, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockService_Expecter) Delete(ctx interface{}, id interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FetchByUserID provides a mock function for the type MockService
func (_mock *MockService) FetchByUserID(ctx context.Context, userID valueobject.UserID) ([]payment_method.PaymentMethod, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByUserID")
	}

	var r0 []payment_method.PaymentMethod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.UserID) ([]payment_method.PaymentMethod, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.UserID) []payment_method.PaymentMethod); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]payment_method.PaymentMethod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, valueobject.UserID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_FetchByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchByUserID'
type MockService_FetchByUserID_Call struct {
	*mock.Call
}

// FetchByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID valueobject.UserID
func (_e *MockService_Expecter) FetchByUserID(ctx interface{}, userID interface{}) *MockService_FetchByUserID_Call {
	return &MockService_FetchByUserID_Call{Call: _e.mock.On("FetchByUserID", ctx, userID)}
}

func (_c *MockService_FetchByUserID_Call) Run(run func(ctx context.Context, userID valueobject.UserID)) *MockService_FetchByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.UserID
		if args[1] != nil {
			arg1 = args[1].(valueobject.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_FetchByUserID_Call) Return(paymentMethods []payment_method.PaymentMethod, err error) *MockService_FetchByUserID_Call {
	_c.Call.Return(paymentMethods, err)
	return _c
}

func (_c *MockService_FetchByUserID_Call) RunAndReturn(run func(ctx context.Context, userID valueobject.UserID) ([]payment_method.PaymentMethod, error)) *MockService_FetchByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockService
func (_mock *MockService) Update(ctx context.Context, id int64, paymentMethod payment_method.PaymentMethod) error {
	ret := _mock.Called(ctx, id, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, payment_method.PaymentMethod) error); ok {
		r0 = returnFunc(ctx, id, paymentMethod)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - paymentMethod payment_method.PaymentMethod
func (_e *MockService_Expecter) Update(ctx interface{}, id interface{}, paymentMethod interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, id, paymentMethod)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, id int64, paymentMethod payment_method.PaymentMethod)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 payment_method.PaymentMethod
		if args[2] != nil {
			arg2 = args[2].(payment_method.PaymentMethod)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Update_Call) Return(err error) *MockService_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(ctx context.Context, id int64, paymentMethod payment_method.PaymentMethod) error) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}
