// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package paymentmethodmock

import (
	"billsplitter-monolith/internal/domain/payment_method"
	"billsplitter-monolith/internal/domain/valueobject"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, method payment_method.PaymentMethod) (payment_method.PaymentMethod, error) {
	ret := _mock.Called(ctx, method)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 payment_method.PaymentMethod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, payment_method.PaymentMethod) (payment_method.PaymentMethod, error)); ok {
		return returnFunc(ctx, method)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, payment_method.PaymentMethod) payment_method.PaymentMethod); ok {
		r0 = returnFunc(ctx, method)
	} else {
		r0 = ret.Get(0).(payment_method.PaymentMethod)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, payment_method.PaymentMethod) error); ok {
		r1 = returnFunc(ctx, method)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - method payment_method.PaymentMethod
func (_e *MockRepository_Expecter) Create(ctx interface{}, method interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, method)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, method payment_method.PaymentMethod)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 payment_method.PaymentMethod
		if args[1] != nil {
			arg1 = args[1].(payment_method.PaymentMethod)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(paymentMethod payment_method.PaymentMethod, err error) *MockRepository_Create_Call {
	_c.Call.Return(paymentMethod, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, method payment_method.PaymentMethod) (payment_method.PaymentMethod, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(err error) *MockRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FetchByUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) FetchByUserID(ctx context.Context, userID valueobject.UserID) ([]payment_method.PaymentMethod, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByUserID")
	}

	var r0 []payment_method.PaymentMethod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.UserID) ([]payment_method.PaymentMethod, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.UserID) []payment_method.PaymentMethod); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]payment_method.PaymentMethod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, valueobject.UserID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FetchByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchByUserID'
type MockRepository_FetchByUserID_Call struct {
	*mock.Call
}

// FetchByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID valueobject.UserID
func (_e *MockRepository_Expecter) FetchByUserID(ctx interface{}, userID interface{}) *MockRepository_FetchByUserID_Call {
	return &MockRepository_FetchByUserID_Call{Call: _e.mock.On("FetchByUserID", ctx, userID)}
}

func (_c *MockRepository_FetchByUserID_Call) Run(run func(ctx context.Context, userID valueobject.UserID)) *MockRepository_FetchByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.UserID
		if args[1] != nil {
			arg1 = args[1].(valueobject.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FetchByUserID_Call) Return(paymentMethods []payment_method.PaymentMethod, err error) *MockRepository_FetchByUserID_Call {
	_c.Call.Return(paymentMethods, err)
	return _c
}

func (_c *MockRepository_FetchByUserID_Call) RunAndReturn(run func(ctx context.Context, userID valueobject.UserID) ([]payment_method.PaymentMethod, error)) *MockRepository_FetchByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByID(ctx context.Context, id int64) (payment_method.PaymentMethod, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 payment_method.PaymentMethod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (payment_method.PaymentMethod, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) payment_method.PaymentMethod); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(payment_method.PaymentMethod)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(paymentMethod payment_method.PaymentMethod, err error) *MockRepository_GetByID_Call {
	_c.Call.Return(paymentMethod, err)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (payment_method.PaymentMethod, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepository
func (_mock *MockRepository) Update(ctx context.Context, id int64, method payment_method.PaymentMethod) error {
	ret := _mock.Called(ctx, id, method)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, payment_method.PaymentMethod) error); ok {
		r0 = returnFunc(ctx, id, method)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - method payment_method.PaymentMethod
func (_e *MockRepository_Expecter) Update(ctx interface{}, id interface{}, method interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, method)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, id int64, method payment_method.PaymentMethod)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 payment_method.PaymentMethod
		if args[2] != nil {
			arg2 = args[2].(payment_method.PaymentMethod)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(err error) *MockRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(ctx context.Context, id int64, method payment_method.PaymentMethod) error) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
