debug: true # включает дебаг логи и в http ответы прокидывает подробные ошибки 
server:
  http:
    port: ":5001" # порт на котором запускается http сервер

telegram:
  bot_token: # токен бота для нотификаций

storage:
  postgres:
    dsn: "postgres://admin:admin@localhost:55433/bill_splitter?sslmode=disable&connect_timeout=5"
