version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: billsplitter-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5001:5001"

volumes:
  pgdata:
