// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package userusecasemock

import (
	"billsplitter-monolith/internal/domain/user"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// GetBySessionID provides a mock function for the type MockUseCase
func (_mock *MockUseCase) GetBySessionID(ctx context.Context, sessionID string) (*user.User, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetBySessionID")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_GetBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySessionID'
type MockUseCase_GetBySessionID_Call struct {
	*mock.Call
}

// GetBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockUseCase_Expecter) GetBySessionID(ctx interface{}, sessionID interface{}) *MockUseCase_GetBySessionID_Call {
	return &MockUseCase_GetBySessionID_Call{Call: _e.mock.On("GetBySessionID", ctx, sessionID)}
}

func (_c *MockUseCase_GetBySessionID_Call) Run(run func(ctx context.Context, sessionID string)) *MockUseCase_GetBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_GetBySessionID_Call) Return(user1 *user.User, err error) *MockUseCase_GetBySessionID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUseCase_GetBySessionID_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (*user.User, error)) *MockUseCase_GetBySessionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTgIDOrCreate provides a mock function for the type MockUseCase
func (_mock *MockUseCase) GetByTgIDOrCreate(ctx context.Context, user1 user.User) (*user.User, error) {
	ret := _mock.Called(ctx, user1)

	if len(ret) == 0 {
		panic("no return value specified for GetByTgIDOrCreate")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) (*user.User, error)); ok {
		return returnFunc(ctx, user1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) *user.User); ok {
		r0 = returnFunc(ctx, user1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.User) error); ok {
		r1 = returnFunc(ctx, user1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_GetByTgIDOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTgIDOrCreate'
type MockUseCase_GetByTgIDOrCreate_Call struct {
	*mock.Call
}

// GetByTgIDOrCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - user1 user.User
func (_e *MockUseCase_Expecter) GetByTgIDOrCreate(ctx interface{}, user1 interface{}) *MockUseCase_GetByTgIDOrCreate_Call {
	return &MockUseCase_GetByTgIDOrCreate_Call{Call: _e.mock.On("GetByTgIDOrCreate", ctx, user1)}
}

func (_c *MockUseCase_GetByTgIDOrCreate_Call) Run(run func(ctx context.Context, user1 user.User)) *MockUseCase_GetByTgIDOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.User
		if args[1] != nil {
			arg1 = args[1].(user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_GetByTgIDOrCreate_Call) Return(user11 *user.User, err error) *MockUseCase_GetByTgIDOrCreate_Call {
	_c.Call.Return(user11, err)
	return _c
}

func (_c *MockUseCase_GetByTgIDOrCreate_Call) RunAndReturn(run func(ctx context.Context, user1 user.User) (*user.User, error)) *MockUseCase_GetByTgIDOrCreate_Call {
	_c.Call.Return(run)
	return _c
}
