// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usermock

import (
	"billsplitter-monolith/internal/domain/user"
	"billsplitter-monolith/internal/domain/valueobject"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, user1 user.User) (*user.User, error) {
	ret := _mock.Called(ctx, user1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) (*user.User, error)); ok {
		return returnFunc(ctx, user1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) *user.User); ok {
		r0 = returnFunc(ctx, user1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.User) error); ok {
		r1 = returnFunc(ctx, user1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user1 user.User
func (_e *MockService_Expecter) Create(ctx interface{}, user1 interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, user1)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, user1 user.User)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.User
		if args[1] != nil {
			arg1 = args[1].(user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(user11 *user.User, err error) *MockService_Create_Call {
	_c.Call.Return(user11, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, user1 user.User) (*user.User, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function for the type MockService
func (_mock *MockService) Fetch(ctx context.Context, filter user.FetchFilter) ([]user.User, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.FetchFilter) ([]user.User, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.FetchFilter) []user.User); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.FetchFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockService_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - filter user.FetchFilter
func (_e *MockService_Expecter) Fetch(ctx interface{}, filter interface{}) *MockService_Fetch_Call {
	return &MockService_Fetch_Call{Call: _e.mock.On("Fetch", ctx, filter)}
}

func (_c *MockService_Fetch_Call) Run(run func(ctx context.Context, filter user.FetchFilter)) *MockService_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.FetchFilter
		if args[1] != nil {
			arg1 = args[1].(user.FetchFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Fetch_Call) Return(users []user.User, err error) *MockService_Fetch_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockService_Fetch_Call) RunAndReturn(run func(ctx context.Context, filter user.FetchFilter) ([]user.User, error)) *MockService_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockService
func (_mock *MockService) GetByID(ctx context.Context, id valueobject.UserID) (*user.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.UserID) (*user.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.UserID) *user.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, valueobject.UserID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id valueobject.UserID
func (_e *MockService_Expecter) GetByID(ctx interface{}, id interface{}) *MockService_GetByID_Call {
	return &MockService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockService_GetByID_Call) Run(run func(ctx context.Context, id valueobject.UserID)) *MockService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.UserID
		if args[1] != nil {
			arg1 = args[1].(valueobject.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetByID_Call) Return(user1 *user.User, err error) *MockService_GetByID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id valueobject.UserID) (*user.User, error)) *MockService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTelegramID provides a mock function for the type MockService
func (_mock *MockService) GetByTelegramID(ctx context.Context, tgID int64) (*user.User, error) {
	ret := _mock.Called(ctx, tgID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTelegramID")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*user.User, error)); ok {
		return returnFunc(ctx, tgID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *user.User); ok {
		r0 = returnFunc(ctx, tgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, tgID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetByTelegramID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTelegramID'
type MockService_GetByTelegramID_Call struct {
	*mock.Call
}

// GetByTelegramID is a helper method to define mock.On call
//   - ctx context.Context
//   - tgID int64
func (_e *MockService_Expecter) GetByTelegramID(ctx interface{}, tgID interface{}) *MockService_GetByTelegramID_Call {
	return &MockService_GetByTelegramID_Call{Call: _e.mock.On("GetByTelegramID", ctx, tgID)}
}

func (_c *MockService_GetByTelegramID_Call) Run(run func(ctx context.Context, tgID int64)) *MockService_GetByTelegramID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetByTelegramID_Call) Return(user1 *user.User, err error) *MockService_GetByTelegramID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockService_GetByTelegramID_Call) RunAndReturn(run func(ctx context.Context, tgID int64) (*user.User, error)) *MockService_GetByTelegramID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockService
func (_mock *MockService) Update(ctx context.Context, id valueobject.UserID, user1 user.User) error {
	ret := _mock.Called(ctx, id, user1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.UserID, user.User) error); ok {
		r0 = returnFunc(ctx, id, user1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id valueobject.UserID
//   - user1 user.User
func (_e *MockService_Expecter) Update(ctx interface{}, id interface{}, user1 interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, id, user1)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, id valueobject.UserID, user1 user.User)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.UserID
		if args[1] != nil {
			arg1 = args[1].(valueobject.UserID)
		}
		var arg2 user.User
		if args[2] != nil {
			arg2 = args[2].(user.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Update_Call) Return(err error) *MockService_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(ctx context.Context, id valueobject.UserID, user1 user.User) error) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}
