// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package eventusecasemock

import (
	event0 "billsplitter-monolith/internal/domain/event"
	"billsplitter-monolith/internal/domain/valueobject"
	"billsplitter-monolith/internal/usecase/event"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// CalculateSummary provides a mock function for the type MockUseCase
func (_mock *MockUseCase) CalculateSummary(ctx context.Context, meetID int64) (*event.EventSummary, error) {
	ret := _mock.Called(ctx, meetID)

	if len(ret) == 0 {
		panic("no return value specified for CalculateSummary")
	}

	var r0 *event.EventSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*event.EventSummary, error)); ok {
		return returnFunc(ctx, meetID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *event.EventSummary); ok {
		r0 = returnFunc(ctx, meetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*event.EventSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, meetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_CalculateSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculateSummary'
type MockUseCase_CalculateSummary_Call struct {
	*mock.Call
}

// CalculateSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - meetID int64
func (_e *MockUseCase_Expecter) CalculateSummary(ctx interface{}, meetID interface{}) *MockUseCase_CalculateSummary_Call {
	return &MockUseCase_CalculateSummary_Call{Call: _e.mock.On("CalculateSummary", ctx, meetID)}
}

func (_c *MockUseCase_CalculateSummary_Call) Run(run func(ctx context.Context, meetID int64)) *MockUseCase_CalculateSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_CalculateSummary_Call) Return(eventSummary *event.EventSummary, err error) *MockUseCase_CalculateSummary_Call {
	_c.Call.Return(eventSummary, err)
	return _c
}

func (_c *MockUseCase_CalculateSummary_Call) RunAndReturn(run func(ctx context.Context, meetID int64) (*event.EventSummary, error)) *MockUseCase_CalculateSummary_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMeet provides a mock function for the type MockUseCase
func (_mock *MockUseCase) CreateMeet(ctx context.Context, rq event.CreateMeetRq) (int64, error) {
	ret := _mock.Called(ctx, rq)

	if len(ret) == 0 {
		panic("no return value specified for CreateMeet")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, event.CreateMeetRq) (int64, error)); ok {
		return returnFunc(ctx, rq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, event.CreateMeetRq) int64); ok {
		r0 = returnFunc(ctx, rq)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, event.CreateMeetRq) error); ok {
		r1 = returnFunc(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_CreateMeet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMeet'
type MockUseCase_CreateMeet_Call struct {
	*mock.Call
}

// CreateMeet is a helper method to define mock.On call
//   - ctx context.Context
//   - rq event.CreateMeetRq
func (_e *MockUseCase_Expecter) CreateMeet(ctx interface{}, rq interface{}) *MockUseCase_CreateMeet_Call {
	return &MockUseCase_CreateMeet_Call{Call: _e.mock.On("CreateMeet", ctx, rq)}
}

func (_c *MockUseCase_CreateMeet_Call) Run(run func(ctx context.Context, rq event.CreateMeetRq)) *MockUseCase_CreateMeet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 event.CreateMeetRq
		if args[1] != nil {
			arg1 = args[1].(event.CreateMeetRq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_CreateMeet_Call) Return(n int64, err error) *MockUseCase_CreateMeet_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUseCase_CreateMeet_Call) RunAndReturn(run func(ctx context.Context, rq event.CreateMeetRq) (int64, error)) *MockUseCase_CreateMeet_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUserMeets provides a mock function for the type MockUseCase
func (_mock *MockUseCase) FetchUserMeets(ctx context.Context, userID valueobject.UserID) ([]event0.Event, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FetchUserMeets")
	}

	var r0 []event0.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.UserID) ([]event0.Event, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.UserID) []event0.Event); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]event0.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, valueobject.UserID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_FetchUserMeets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUserMeets'
type MockUseCase_FetchUserMeets_Call struct {
	*mock.Call
}

// FetchUserMeets is a helper method to define mock.On call
//   - ctx context.Context
//   - userID valueobject.UserID
func (_e *MockUseCase_Expecter) FetchUserMeets(ctx interface{}, userID interface{}) *MockUseCase_FetchUserMeets_Call {
	return &MockUseCase_FetchUserMeets_Call{Call: _e.mock.On("FetchUserMeets", ctx, userID)}
}

func (_c *MockUseCase_FetchUserMeets_Call) Run(run func(ctx context.Context, userID valueobject.UserID)) *MockUseCase_FetchUserMeets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.UserID
		if args[1] != nil {
			arg1 = args[1].(valueobject.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_FetchUserMeets_Call) Return(events []event0.Event, err error) *MockUseCase_FetchUserMeets_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockUseCase_FetchUserMeets_Call) RunAndReturn(run func(ctx context.Context, userID valueobject.UserID) ([]event0.Event, error)) *MockUseCase_FetchUserMeets_Call {
	_c.Call.Return(run)
	return _c
}

// GetMeetByID provides a mock function for the type MockUseCase
func (_mock *MockUseCase) GetMeetByID(ctx context.Context, meetID int64) (*event0.Event, error) {
	ret := _mock.Called(ctx, meetID)

	if len(ret) == 0 {
		panic("no return value specified for GetMeetByID")
	}

	var r0 *event0.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*event0.Event, error)); ok {
		return returnFunc(ctx, meetID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *event0.Event); ok {
		r0 = returnFunc(ctx, meetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*event0.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, meetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_GetMeetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMeetByID'
type MockUseCase_GetMeetByID_Call struct {
	*mock.Call
}

// GetMeetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - meetID int64
func (_e *MockUseCase_Expecter) GetMeetByID(ctx interface{}, meetID interface{}) *MockUseCase_GetMeetByID_Call {
	return &MockUseCase_GetMeetByID_Call{Call: _e.mock.On("GetMeetByID", ctx, meetID)}
}

func (_c *MockUseCase_GetMeetByID_Call) Run(run func(ctx context.Context, meetID int64)) *MockUseCase_GetMeetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_GetMeetByID_Call) Return(event1 *event0.Event, err error) *MockUseCase_GetMeetByID_Call {
	_c.Call.Return(event1, err)
	return _c
}

func (_c *MockUseCase_GetMeetByID_Call) RunAndReturn(run func(ctx context.Context, meetID int64) (*event0.Event, error)) *MockUseCase_GetMeetByID_Call {
	_c.Call.Return(run)
	return _c
}

// AssignMemberToUser provides a mock function for the type MockUseCase
func (_mock *MockUseCase) AssignMemberToUser(ctx context.Context, meetID int64, memberID int64, userID valueobject.UserID) error {
	ret := _mock.Called(ctx, meetID, memberID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AssignMemberToUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, valueobject.UserID) error); ok {
		r0 = returnFunc(ctx, meetID, memberID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUseCase_AssignMemberToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignMemberToUser'
type MockUseCase_AssignMemberToUser_Call struct {
	*mock.Call
}

// AssignMemberToUser is a helper method to define mock.On call
//   - ctx context.Context
//   - meetID int64
//   - memberID int64
//   - userID valueobject.UserID
func (_e *MockUseCase_Expecter) AssignMemberToUser(ctx interface{}, meetID interface{}, memberID interface{}, userID interface{}) *MockUseCase_AssignMemberToUser_Call {
	return &MockUseCase_AssignMemberToUser_Call{Call: _e.mock.On("AssignMemberToUser", ctx, meetID, memberID, userID)}
}

func (_c *MockUseCase_AssignMemberToUser_Call) Run(run func(ctx context.Context, meetID int64, memberID int64, userID valueobject.UserID)) *MockUseCase_AssignMemberToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 valueobject.UserID
		if args[3] != nil {
			arg3 = args[3].(valueobject.UserID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUseCase_AssignMemberToUser_Call) Return(err error) *MockUseCase_AssignMemberToUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUseCase_AssignMemberToUser_Call) RunAndReturn(run func(ctx context.Context, meetID int64, memberID int64, userID valueobject.UserID) error) *MockUseCase_AssignMemberToUser_Call {
	_c.Call.Return(run)
	return _c
}
