// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package billusecasemock

import (
	bill0 "billsplitter-monolith/internal/domain/bill"
	"billsplitter-monolith/internal/usecase/bill"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// CreateBill provides a mock function for the type MockUseCase
func (_mock *MockUseCase) CreateBill(ctx context.Context, rq bill.CreateBillRq) (int64, error) {
	ret := _mock.Called(ctx, rq)

	if len(ret) == 0 {
		panic("no return value specified for CreateBill")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bill.CreateBillRq) (int64, error)); ok {
		return returnFunc(ctx, rq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bill.CreateBillRq) int64); ok {
		r0 = returnFunc(ctx, rq)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bill.CreateBillRq) error); ok {
		r1 = returnFunc(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_CreateBill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBill'
type MockUseCase_CreateBill_Call struct {
	*mock.Call
}

// CreateBill is a helper method to define mock.On call
//   - ctx context.Context
//   - rq bill.CreateBillRq
func (_e *MockUseCase_Expecter) CreateBill(ctx interface{}, rq interface{}) *MockUseCase_CreateBill_Call {
	return &MockUseCase_CreateBill_Call{Call: _e.mock.On("CreateBill", ctx, rq)}
}

func (_c *MockUseCase_CreateBill_Call) Run(run func(ctx context.Context, rq bill.CreateBillRq)) *MockUseCase_CreateBill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bill.CreateBillRq
		if args[1] != nil {
			arg1 = args[1].(bill.CreateBillRq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_CreateBill_Call) Return(n int64, err error) *MockUseCase_CreateBill_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUseCase_CreateBill_Call) RunAndReturn(run func(ctx context.Context, rq bill.CreateBillRq) (int64, error)) *MockUseCase_CreateBill_Call {
	_c.Call.Return(run)
	return _c
}

// FetchEventBills provides a mock function for the type MockUseCase
func (_mock *MockUseCase) FetchEventBills(ctx context.Context, eventID int64) ([]bill0.Bill, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for FetchEventBills")
	}

	var r0 []bill0.Bill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]bill0.Bill, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []bill0.Bill); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bill0.Bill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_FetchEventBills_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchEventBills'
type MockUseCase_FetchEventBills_Call struct {
	*mock.Call
}

// FetchEventBills is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int64
func (_e *MockUseCase_Expecter) FetchEventBills(ctx interface{}, eventID interface{}) *MockUseCase_FetchEventBills_Call {
	return &MockUseCase_FetchEventBills_Call{Call: _e.mock.On("FetchEventBills", ctx, eventID)}
}

func (_c *MockUseCase_FetchEventBills_Call) Run(run func(ctx context.Context, eventID int64)) *MockUseCase_FetchEventBills_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_FetchEventBills_Call) Return(bills []bill0.Bill, err error) *MockUseCase_FetchEventBills_Call {
	_c.Call.Return(bills, err)
	return _c
}

func (_c *MockUseCase_FetchEventBills_Call) RunAndReturn(run func(ctx context.Context, eventID int64) ([]bill0.Bill, error)) *MockUseCase_FetchEventBills_Call {
	_c.Call.Return(run)
	return _c
}
