// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package billmock

import (
	"billsplitter-monolith/internal/domain/bill"
	"billsplitter-monolith/internal/domain/valueobject"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AddUsers provides a mock function for the type MockService
func (_mock *MockService) AddUsers(ctx context.Context, billID int64, users []valueobject.UserID) error {
	ret := _mock.Called(ctx, billID, users)

	if len(ret) == 0 {
		panic("no return value specified for AddUsers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []valueobject.UserID) error); ok {
		r0 = returnFunc(ctx, billID, users)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_AddUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUsers'
type MockService_AddUsers_Call struct {
	*mock.Call
}

// AddUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - billID int64
//   - users []valueobject.UserID
func (_e *MockService_Expecter) AddUsers(ctx interface{}, billID interface{}, users interface{}) *MockService_AddUsers_Call {
	return &MockService_AddUsers_Call{Call: _e.mock.On("AddUsers", ctx, billID, users)}
}

func (_c *MockService_AddUsers_Call) Run(run func(ctx context.Context, billID int64, users []valueobject.UserID)) *MockService_AddUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []valueobject.UserID
		if args[2] != nil {
			arg2 = args[2].([]valueobject.UserID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_AddUsers_Call) Return(err error) *MockService_AddUsers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_AddUsers_Call) RunAndReturn(run func(ctx context.Context, billID int64, users []valueobject.UserID) error) *MockService_AddUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, bill1 bill.Bill) (int64, error) {
	ret := _mock.Called(ctx, bill1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bill.Bill) (int64, error)); ok {
		return returnFunc(ctx, bill1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bill.Bill) int64); ok {
		r0 = returnFunc(ctx, bill1)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bill.Bill) error); ok {
		r1 = returnFunc(ctx, bill1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - bill1 bill.Bill
func (_e *MockService_Expecter) Create(ctx interface{}, bill1 interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, bill1)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, bill1 bill.Bill)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bill.Bill
		if args[1] != nil {
			arg1 = args[1].(bill.Bill)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(n int64, err error) *MockService_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, bill1 bill.Bill) (int64, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(ctx context.Context, billID int64) error {
	ret := _mock.Called(ctx, billID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, billID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - billID int64
func (_e *MockService_Expecter) Delete(ctx interface{}, billID interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, billID)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, billID int64)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(ctx context.Context, billID int64) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FetchByEventID provides a mock function for the type MockService
func (_mock *MockService) FetchByEventID(ctx context.Context, eventID int64) ([]bill.Bill, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByEventID")
	}

	var r0 []bill.Bill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]bill.Bill, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []bill.Bill); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bill.Bill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_FetchByEventID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchByEventID'
type MockService_FetchByEventID_Call struct {
	*mock.Call
}

// FetchByEventID is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int64
func (_e *MockService_Expecter) FetchByEventID(ctx interface{}, eventID interface{}) *MockService_FetchByEventID_Call {
	return &MockService_FetchByEventID_Call{Call: _e.mock.On("FetchByEventID", ctx, eventID)}
}

func (_c *MockService_FetchByEventID_Call) Run(run func(ctx context.Context, eventID int64)) *MockService_FetchByEventID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_FetchByEventID_Call) Return(bills []bill.Bill, err error) *MockService_FetchByEventID_Call {
	_c.Call.Return(bills, err)
	return _c
}

func (_c *MockService_FetchByEventID_Call) RunAndReturn(run func(ctx context.Context, eventID int64) ([]bill.Bill, error)) *MockService_FetchByEventID_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUsers provides a mock function for the type MockService
func (_mock *MockService) RemoveUsers(ctx context.Context, billID int64, users []valueobject.UserID) error {
	ret := _mock.Called(ctx, billID, users)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUsers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []valueobject.UserID) error); ok {
		r0 = returnFunc(ctx, billID, users)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RemoveUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUsers'
type MockService_RemoveUsers_Call struct {
	*mock.Call
}

// RemoveUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - billID int64
//   - users []valueobject.UserID
func (_e *MockService_Expecter) RemoveUsers(ctx interface{}, billID interface{}, users interface{}) *MockService_RemoveUsers_Call {
	return &MockService_RemoveUsers_Call{Call: _e.mock.On("RemoveUsers", ctx, billID, users)}
}

func (_c *MockService_RemoveUsers_Call) Run(run func(ctx context.Context, billID int64, users []valueobject.UserID)) *MockService_RemoveUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []valueobject.UserID
		if args[2] != nil {
			arg2 = args[2].([]valueobject.UserID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_RemoveUsers_Call) Return(err error) *MockService_RemoveUsers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RemoveUsers_Call) RunAndReturn(run func(ctx context.Context, billID int64, users []valueobject.UserID) error) *MockService_RemoveUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockService
func (_mock *MockService) Update(ctx context.Context, rq bill.UpdateBillRq) error {
	ret := _mock.Called(ctx, rq)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bill.UpdateBillRq) error); ok {
		r0 = returnFunc(ctx, rq)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - rq bill.UpdateBillRq
func (_e *MockService_Expecter) Update(ctx interface{}, rq interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, rq)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, rq bill.UpdateBillRq)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bill.UpdateBillRq
		if args[1] != nil {
			arg1 = args[1].(bill.UpdateBillRq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Update_Call) Return(err error) *MockService_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(ctx context.Context, rq bill.UpdateBillRq) error) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}
