// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login/telegram": {
            "post": {
                "description": "Создаёт или получает пользователя по Telegram ID и возвращает sessionID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Авторизация через Telegram",
                "parameters": [
                    {
                        "description": "Данные пользователя из Telegram",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http_auth.LoginTelegramReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http_auth.LoginTelegramRes"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error, но в debug моде возвращает детали ошибки",
                        "schema": {
                            "$ref": "#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "description": "Возвращает данные пользователя, извлечённые по sessionID из контекста",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Получить данные текущего пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http_auth.MeRes"
                        }
                    },
                    "400": {
                        "description": "Пользователь не найден или сессия невалидна",
                        "schema": {
                            "$ref": "#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/event": {
            "post": {
                "description": "Создает новый мит с участниками",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meet"
                ],
                "summary": "Создает новый мит",
                "parameters": [
                    {
                        "description": "Данные мита",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http_meet.CreateEventRq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "ID созданного мита",
                        "schema": {
                            "$ref": "#/definitions/billsplitter-monolith_internal_utils_http.ResponseID"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/{id}/profile": {
            "put": {
                "description": "Обновляет профиль пользователя по переданному ID, если пользователь аутентифицирован и имеет доступ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Обновление профиля пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления профиля",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http_user.UpdateUserProfileReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Профиль успешно обновлён",
                        "schema": {
                            "$ref": "#/definitions/billsplitter-monolith_internal_utils_http.ResponseOK"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос или ошибка сессии",
                        "schema": {
                            "$ref": "#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещён (несовпадение ID пользователя и сессии)",
                        "schema": {
                            "$ref": "#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера (в debug режиме — детали)",
                        "schema": {
                            "$ref": "#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "billsplitter-monolith_internal_domain_user.ExtraInfo": {
            "type": "object",
            "properties": {
                "telegram_id": {
                    "type": "integer"
                }
            }
        },
        "billsplitter-monolith_internal_domain_user.User": {
            "type": "object",
            "properties": {
                "extra": {
                    "$ref": "#/definitions/billsplitter-monolith_internal_domain_user.ExtraInfo"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "billsplitter-monolith_internal_utils_http.ErrorResponse": {
            "type": "object",
            "properties": {
                "errorMessage": {
                    "type": "string"
                }
            }
        },
        "billsplitter-monolith_internal_utils_http.ResponseID": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "billsplitter-monolith_internal_utils_http.ResponseOK": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http_auth.LoginTelegramReq": {
            "type": "object",
            "required": [
                "telegramID"
            ],
            "properties": {
                "firstName": {
                    "type": "string",
                    "example": "John"
                },
                "lastName": {
                    "type": "string",
                    "example": "Doe"
                },
                "telegramID": {
                    "type": "integer",
                    "example": 123456789
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "internal_transport_http_auth.LoginTelegramRes": {
            "type": "object",
            "properties": {
                "sessionID": {
                    "type": "string",
                    "example": "b42b0a8e-0d1f-4c3d-939f-85fbbdc9be62"
                },
                "userInfo": {
                    "$ref": "#/definitions/billsplitter-monolith_internal_domain_user.User"
                }
            }
        },
        "internal_transport_http_auth.MeRes": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/billsplitter-monolith_internal_domain_user.User"
                }
            }
        },
        "internal_transport_http_meet.CreateEventRq": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http_user.UpdateUserProfileReq": {
            "type": "object",
            "properties": {
                "firstName": {
                    "type": "string",
                    "example": "John"
                },
                "lastName": {
                    "type": "string",
                    "example": "Doe"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5001",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "BillSplitter API",
	Description:      "API для Telegram Mini App по разделению счетов",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
