basePath: /
definitions:
  billsplitter-monolith_internal_domain_user.ExtraInfo:
    properties:
      telegram_id:
        type: integer
    type: object
  billsplitter-monolith_internal_domain_user.User:
    properties:
      extra:
        $ref: '#/definitions/billsplitter-monolith_internal_domain_user.ExtraInfo'
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
      username:
        type: string
    type: object
  billsplitter-monolith_internal_utils_http.ErrorResponse:
    properties:
      errorMessage:
        type: string
    type: object
  billsplitter-monolith_internal_utils_http.ResponseID:
    properties:
      id:
        type: integer
    type: object
  billsplitter-monolith_internal_utils_http.ResponseOK:
    properties:
      message:
        type: string
    type: object
  internal_transport_http_auth.LoginTelegramReq:
    properties:
      firstName:
        example: John
        type: string
      lastName:
        example: Doe
        type: string
      telegramID:
        example: 123456789
        type: integer
      username:
        example: johndoe
        type: string
    required:
    - telegramID
    type: object
  internal_transport_http_auth.LoginTelegramRes:
    properties:
      sessionID:
        example: b42b0a8e-0d1f-4c3d-939f-85fbbdc9be62
        type: string
      userInfo:
        $ref: '#/definitions/billsplitter-monolith_internal_domain_user.User'
    type: object
  internal_transport_http_auth.MeRes:
    properties:
      user:
        $ref: '#/definitions/billsplitter-monolith_internal_domain_user.User'
    type: object
  internal_transport_http_meet.CreateEventRq:
    properties:
      date:
        type: string
      members:
        items:
          type: string
        type: array
      name:
        type: string
    type: object
  internal_transport_http_meet.Event:
    properties:
      ID:
        type: integer
      created_at:
        type: string
      created_by_user_id:
        type: integer
      deleted_at:
        type: string
      event_date:
        type: string
      members:
        items:
          $ref: '#/definitions/internal_transport_http_meet.Member'
        type: array
      name:
        type: string
      status:
        type: string
      type:
        type: string
      updated_at:
        type: string
    type: object
  internal_transport_http_meet.Member:
    properties:
      user_id:
        type: integer
      username:
        type: string
    type: object
  internal_transport_http_user.UpdateUserProfileReq:
    properties:
      firstName:
        example: John
        type: string
      lastName:
        example: Doe
        type: string
      username:
        example: johndoe
        type: string
    type: object
host: localhost:5001
info:
  contact: {}
  description: API для Telegram Mini App по разделению счетов
  title: BillSplitter API
  version: "1.0"
paths:
  /auth/login/telegram:
    post:
      consumes:
      - application/json
      description: Создаёт или получает пользователя по Telegram ID и возвращает sessionID
      parameters:
      - description: Данные пользователя из Telegram
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_transport_http_auth.LoginTelegramReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_transport_http_auth.LoginTelegramRes'
        "400":
          description: Некорректный запрос
          schema:
            $ref: '#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse'
        "500":
          description: Internal Server Error, но в debug моде возвращает детали ошибки
          schema:
            $ref: '#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse'
      summary: Авторизация через Telegram
      tags:
      - auth
  /auth/me:
    get:
      description: Возвращает данные пользователя, извлечённые по sessionID из контекста
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_transport_http_auth.MeRes'
        "400":
          description: Пользователь не найден или сессия невалидна
          schema:
            $ref: '#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse'
      summary: Получить данные текущего пользователя
      tags:
      - auth
  /meets:
    get:
      consumes:
      - application/json
      description: ID юзера берется из сессии
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_transport_http_meet.Event'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Получение персонального списка ивентов
      tags:
      - meet
    post:
      consumes:
      - application/json
      description: Создает новый мит с участниками
      parameters:
      - description: Данные мита
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_transport_http_meet.CreateEventRq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/billsplitter-monolith_internal_utils_http.ResponseID'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Создает новый мит
      tags:
      - meet
  /meets/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: ID мита
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_transport_http_meet.Event'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Получение инфы по ивенту
      tags:
      - meet
  /user/{id}/profile:
    put:
      consumes:
      - application/json
      description: Обновляет профиль пользователя по переданному ID, если пользователь
        аутентифицирован и имеет доступ
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      - description: Данные для обновления профиля
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_transport_http_user.UpdateUserProfileReq'
      produces:
      - application/json
      responses:
        "200":
          description: Профиль успешно обновлён
          schema:
            $ref: '#/definitions/billsplitter-monolith_internal_utils_http.ResponseOK'
        "400":
          description: Некорректный запрос или ошибка сессии
          schema:
            $ref: '#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse'
        "403":
          description: Доступ запрещён (несовпадение ID пользователя и сессии)
          schema:
            $ref: '#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера (в debug режиме — детали)
          schema:
            $ref: '#/definitions/billsplitter-monolith_internal_utils_http.ErrorResponse'
      summary: Обновление профиля пользователя
      tags:
      - user
schemes:
- http
swagger: "2.0"
