// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package eventmock

import (
	"billsplitter-monolith/internal/domain/event"
	"billsplitter-monolith/internal/domain/valueobject"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AddUsers provides a mock function for the type MockService
func (_mock *MockService) AddUsers(ctx context.Context, eventID int64, userID []valueobject.UserID) error {
	ret := _mock.Called(ctx, eventID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddUsers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []valueobject.UserID) error); ok {
		r0 = returnFunc(ctx, eventID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_AddUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUsers'
type MockService_AddUsers_Call struct {
	*mock.Call
}

// AddUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int64
//   - userID []valueobject.UserID
func (_e *MockService_Expecter) AddUsers(ctx interface{}, eventID interface{}, userID interface{}) *MockService_AddUsers_Call {
	return &MockService_AddUsers_Call{Call: _e.mock.On("AddUsers", ctx, eventID, userID)}
}

func (_c *MockService_AddUsers_Call) Run(run func(ctx context.Context, eventID int64, userID []valueobject.UserID)) *MockService_AddUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []valueobject.UserID
		if args[2] != nil {
			arg2 = args[2].([]valueobject.UserID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_AddUsers_Call) Return(err error) *MockService_AddUsers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_AddUsers_Call) RunAndReturn(run func(ctx context.Context, eventID int64, userID []valueobject.UserID) error) *MockService_AddUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, event1 event.CreateEventRq) (int64, error) {
	ret := _mock.Called(ctx, event1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, event.CreateEventRq) (int64, error)); ok {
		return returnFunc(ctx, event1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, event.CreateEventRq) int64); ok {
		r0 = returnFunc(ctx, event1)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, event.CreateEventRq) error); ok {
		r1 = returnFunc(ctx, event1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - event1 event.CreateEventRq
func (_e *MockService_Expecter) Create(ctx interface{}, event1 interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, event1)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, event1 event.CreateEventRq)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 event.CreateEventRq
		if args[1] != nil {
			arg1 = args[1].(event.CreateEventRq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(n int64, err error) *MockService_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, event1 event.CreateEventRq) (int64, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(ctx context.Context, billID int64) error {
	ret := _mock.Called(ctx, billID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, billID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - billID int64
func (_e *MockService_Expecter) Delete(ctx interface{}, billID interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, billID)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, billID int64)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(ctx context.Context, billID int64) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FetchByUserID provides a mock function for the type MockService
func (_mock *MockService) FetchByUserID(ctx context.Context, userID valueobject.UserID) ([]event.Event, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByUserID")
	}

	var r0 []event.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.UserID) ([]event.Event, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.UserID) []event.Event); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]event.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, valueobject.UserID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_FetchByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchByUserID'
type MockService_FetchByUserID_Call struct {
	*mock.Call
}

// FetchByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID valueobject.UserID
func (_e *MockService_Expecter) FetchByUserID(ctx interface{}, userID interface{}) *MockService_FetchByUserID_Call {
	return &MockService_FetchByUserID_Call{Call: _e.mock.On("FetchByUserID", ctx, userID)}
}

func (_c *MockService_FetchByUserID_Call) Run(run func(ctx context.Context, userID valueobject.UserID)) *MockService_FetchByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.UserID
		if args[1] != nil {
			arg1 = args[1].(valueobject.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_FetchByUserID_Call) Return(events []event.Event, err error) *MockService_FetchByUserID_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockService_FetchByUserID_Call) RunAndReturn(run func(ctx context.Context, userID valueobject.UserID) ([]event.Event, error)) *MockService_FetchByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockService
func (_mock *MockService) GetByID(ctx context.Context, eventID int64) (*event.Event, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *event.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*event.Event, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *event.Event); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*event.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int64
func (_e *MockService_Expecter) GetByID(ctx interface{}, eventID interface{}) *MockService_GetByID_Call {
	return &MockService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, eventID)}
}

func (_c *MockService_GetByID_Call) Run(run func(ctx context.Context, eventID int64)) *MockService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetByID_Call) Return(event1 *event.Event, err error) *MockService_GetByID_Call {
	_c.Call.Return(event1, err)
	return _c
}

func (_c *MockService_GetByID_Call) RunAndReturn(run func(ctx context.Context, eventID int64) (*event.Event, error)) *MockService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUsers provides a mock function for the type MockService
func (_mock *MockService) RemoveUsers(ctx context.Context, eventID int64, userID []valueobject.UserID) error {
	ret := _mock.Called(ctx, eventID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUsers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []valueobject.UserID) error); ok {
		r0 = returnFunc(ctx, eventID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RemoveUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUsers'
type MockService_RemoveUsers_Call struct {
	*mock.Call
}

// RemoveUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int64
//   - userID []valueobject.UserID
func (_e *MockService_Expecter) RemoveUsers(ctx interface{}, eventID interface{}, userID interface{}) *MockService_RemoveUsers_Call {
	return &MockService_RemoveUsers_Call{Call: _e.mock.On("RemoveUsers", ctx, eventID, userID)}
}

func (_c *MockService_RemoveUsers_Call) Run(run func(ctx context.Context, eventID int64, userID []valueobject.UserID)) *MockService_RemoveUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []valueobject.UserID
		if args[2] != nil {
			arg2 = args[2].([]valueobject.UserID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_RemoveUsers_Call) Return(err error) *MockService_RemoveUsers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RemoveUsers_Call) RunAndReturn(run func(ctx context.Context, eventID int64, userID []valueobject.UserID) error) *MockService_RemoveUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockService
func (_mock *MockService) Update(ctx context.Context, rq event.UpdateEventRq) error {
	ret := _mock.Called(ctx, rq)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, event.UpdateEventRq) error); ok {
		r0 = returnFunc(ctx, rq)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - rq event.UpdateEventRq
func (_e *MockService_Expecter) Update(ctx interface{}, rq interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, rq)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, rq event.UpdateEventRq)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 event.UpdateEventRq
		if args[1] != nil {
			arg1 = args[1].(event.UpdateEventRq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Update_Call) Return(err error) *MockService_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(ctx context.Context, rq event.UpdateEventRq) error) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// AssignMemberUser provides a mock function for the type MockService
func (_mock *MockService) AssignMemberUser(ctx context.Context, eventID int64, memberID int64, userID valueobject.UserID) error {
	ret := _mock.Called(ctx, eventID, memberID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AssignMemberUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, valueobject.UserID) error); ok {
		r0 = returnFunc(ctx, eventID, memberID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_AssignMemberUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignMemberUser'
type MockService_AssignMemberUser_Call struct {
	*mock.Call
}

// AssignMemberUser is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int64
//   - memberID int64
//   - userID valueobject.UserID
func (_e *MockService_Expecter) AssignMemberUser(ctx interface{}, eventID interface{}, memberID interface{}, userID interface{}) *MockService_AssignMemberUser_Call {
	return &MockService_AssignMemberUser_Call{Call: _e.mock.On("AssignMemberUser", ctx, eventID, memberID, userID)}
}

func (_c *MockService_AssignMemberUser_Call) Run(run func(ctx context.Context, eventID int64, memberID int64, userID valueobject.UserID)) *MockService_AssignMemberUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 valueobject.UserID
		if args[3] != nil {
			arg3 = args[3].(valueobject.UserID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_AssignMemberUser_Call) Return(err error) *MockService_AssignMemberUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_AssignMemberUser_Call) RunAndReturn(run func(ctx context.Context, eventID int64, memberID int64, userID valueobject.UserID) error) *MockService_AssignMemberUser_Call {
	_c.Call.Return(run)
	return _c
}
