// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package eventmock

import (
	"billsplitter-monolith/internal/domain/event"
	"billsplitter-monolith/internal/domain/valueobject"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddMembers provides a mock function for the type MockRepository
func (_mock *MockRepository) AddMembers(ctx context.Context, eventID int64, members []event.Member) error {
	ret := _mock.Called(ctx, eventID, members)

	if len(ret) == 0 {
		panic("no return value specified for AddMembers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []event.Member) error); ok {
		r0 = returnFunc(ctx, eventID, members)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AddMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMembers'
type MockRepository_AddMembers_Call struct {
	*mock.Call
}

// AddMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int64
//   - members []event.Member
func (_e *MockRepository_Expecter) AddMembers(ctx interface{}, eventID interface{}, members interface{}) *MockRepository_AddMembers_Call {
	return &MockRepository_AddMembers_Call{Call: _e.mock.On("AddMembers", ctx, eventID, members)}
}

func (_c *MockRepository_AddMembers_Call) Run(run func(ctx context.Context, eventID int64, members []event.Member)) *MockRepository_AddMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []event.Member
		if args[2] != nil {
			arg2 = args[2].([]event.Member)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_AddMembers_Call) Return(err error) *MockRepository_AddMembers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AddMembers_Call) RunAndReturn(run func(ctx context.Context, eventID int64, members []event.Member) error) *MockRepository_AddMembers_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, event1 event.Event) (int64, error) {
	ret := _mock.Called(ctx, event1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, event.Event) (int64, error)); ok {
		return returnFunc(ctx, event1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, event.Event) int64); ok {
		r0 = returnFunc(ctx, event1)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, event.Event) error); ok {
		r1 = returnFunc(ctx, event1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - event1 event.Event
func (_e *MockRepository_Expecter) Create(ctx interface{}, event1 interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, event1)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, event1 event.Event)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 event.Event
		if args[1] != nil {
			arg1 = args[1].(event.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(n int64, err error) *MockRepository_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, event1 event.Event) (int64, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FetchByUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) FetchByUserID(ctx context.Context, userID valueobject.UserID) ([]event.Event, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByUserID")
	}

	var r0 []event.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.UserID) ([]event.Event, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.UserID) []event.Event); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]event.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, valueobject.UserID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FetchByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchByUserID'
type MockRepository_FetchByUserID_Call struct {
	*mock.Call
}

// FetchByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID valueobject.UserID
func (_e *MockRepository_Expecter) FetchByUserID(ctx interface{}, userID interface{}) *MockRepository_FetchByUserID_Call {
	return &MockRepository_FetchByUserID_Call{Call: _e.mock.On("FetchByUserID", ctx, userID)}
}

func (_c *MockRepository_FetchByUserID_Call) Run(run func(ctx context.Context, userID valueobject.UserID)) *MockRepository_FetchByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.UserID
		if args[1] != nil {
			arg1 = args[1].(valueobject.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FetchByUserID_Call) Return(events []event.Event, err error) *MockRepository_FetchByUserID_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockRepository_FetchByUserID_Call) RunAndReturn(run func(ctx context.Context, userID valueobject.UserID) ([]event.Event, error)) *MockRepository_FetchByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByID(ctx context.Context, eventID int64) (*event.Event, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *event.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*event.Event, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *event.Event); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*event.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GetByPublicUUID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByPublicUUID(ctx context.Context, publicUUID string) (*event.Event, error) {
	ret := _mock.Called(ctx, publicUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetByPublicUUID")
	}

	var r0 *event.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*event.Event, error)); ok {
		return returnFunc(ctx, publicUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *event.Event); ok {
		r0 = returnFunc(ctx, publicUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*event.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, publicUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByPublicUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPublicUUID'
type MockRepository_GetByPublicUUID_Call struct {
	*mock.Call
}

// GetByPublicUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - publicUUID string
func (_e *MockRepository_Expecter) GetByPublicUUID(ctx interface{}, publicUUID interface{}) *MockRepository_GetByPublicUUID_Call {
	return &MockRepository_GetByPublicUUID_Call{Call: _e.mock.On("GetByPublicUUID", ctx, publicUUID)}
}

func (_c *MockRepository_GetByPublicUUID_Call) Run(run func(ctx context.Context, publicUUID string)) *MockRepository_GetByPublicUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByPublicUUID_Call) Return(event1 *event.Event, err error) *MockRepository_GetByPublicUUID_Call {
	_c.Call.Return(event1, err)
	return _c
}

func (_c *MockRepository_GetByPublicUUID_Call) RunAndReturn(run func(ctx context.Context, publicUUID string) (*event.Event, error)) *MockRepository_GetByPublicUUID_Call {
	_c.Call.Return(run)
	return _c
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int64
func (_e *MockRepository_Expecter) GetByID(ctx interface{}, eventID interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, eventID)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, eventID int64)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(event1 *event.Event, err error) *MockRepository_GetByID_Call {
	_c.Call.Return(event1, err)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, eventID int64) (*event.Event, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// AssignMemberUser provides a mock function for the type MockRepository
func (_mock *MockRepository) AssignMemberUser(ctx context.Context, eventID int64, memberID int64, userID valueobject.UserID) error {
	ret := _mock.Called(ctx, eventID, memberID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AssignMemberUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, valueobject.UserID) error); ok {
		r0 = returnFunc(ctx, eventID, memberID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AssignMemberUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignMemberUser'
type MockRepository_AssignMemberUser_Call struct {
	*mock.Call
}

// AssignMemberUser is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int64
//   - memberID int64
//   - userID valueobject.UserID
func (_e *MockRepository_Expecter) AssignMemberUser(ctx interface{}, eventID interface{}, memberID interface{}, userID interface{}) *MockRepository_AssignMemberUser_Call {
	return &MockRepository_AssignMemberUser_Call{Call: _e.mock.On("AssignMemberUser", ctx, eventID, memberID, userID)}
}

func (_c *MockRepository_AssignMemberUser_Call) Run(run func(ctx context.Context, eventID int64, memberID int64, userID valueobject.UserID)) *MockRepository_AssignMemberUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 valueobject.UserID
		if args[3] != nil {
			arg3 = args[3].(valueobject.UserID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_AssignMemberUser_Call) Return(err error) *MockRepository_AssignMemberUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AssignMemberUser_Call) RunAndReturn(run func(ctx context.Context, eventID int64, memberID int64, userID valueobject.UserID) error) *MockRepository_AssignMemberUser_Call {
	_c.Call.Return(run)
	return _c
}
